# Generated by Django 5.2.6 on 2025-10-13 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_transaction_wallet_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
