# Generated by Django 5.2.6 on 2025-10-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
